# Azure pipeline yaml script for building react app.

trigger:
- main

pool:
  name: Default

steps:
- script: npm install
  displayName: 'Install Binaries'

- script: npm run build
  displayName: 'Build React App'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/build'
    ArtifactName: 'react-app'
    publishLocation: 'Container'